### ISSUE TITLE
Wayland prerequisites checklist

### ISSUE THREAD

**Issue by TolikPylypchuk** [TolikPylypchuk/KeyboardSwitch#54]
Before KeyboardSwitch can work on Wayland natively, I need to check the following things:
- [x] AvaloniaUI supports Wayland
- [x] libuiohook supports Wayland
- [x] ~~TextCopy supports Wayland~~
- [ ] I have a least the slightest idea about manipulating keyboard layouts with Wayland

**Comment by TolikPylypchuk** [comment]
No need for TextCopy supporting Wayland since I've reimplemented clipboard interop directly in Keyboard Switch. Now I will need to implement it for Wayland as well, but that seems manageable - I've copied the X11 implementation from Avalonia, I will most probably do the same for Wayland.

**Comment by nativescriptdev-ux** [comment]
From what I understand , Wayland is problematic both for clipboard & detect layouts &  change layouts by code.
They pretty much blocked everything there
Can it be solved ?

**Comment by TolikPylypchuk** [comment]
Regarding the clipboard, there's the wl-clipboard utility for Wayland, so this is 100% possible.

Regarding keyboard layouts, I don't know, I haven't investigated this aspect yet.

**Comment by nativescriptdev-ux** [comment]
@TolikPylypchuk keyboard layout for getting the mapping you mean ?

**Comment by TolikPylypchuk** [comment]
Yes, getting the current layout, the list of all layouts, and changing layouts programmatically - I haven't yet investigated any of that.

**Comment by TolikPylypchuk** [comment]
I've just released SharpHook 8 which adds Wayland support. I've also looked into keyboard layout management - unfortunately, Wayland doesn't have any protocols for this, so this will have to be done per compositor.

I'm closing this issue since the prerequisites for Wayland are done.
